# Modifier Configuration File
#
# Each modifier is associated with different rarities and has an associated weight.
# The `hasValues` field indicates whether the modifier requires a specific range of values.
# If `hasValues` is true, the `values` section specifies the minimum and maximum values for each rarity.
# The `increment` field specifies the step size between the min and max values for modifiers with value ranges.
#
# Modifiers with `hasValues` set to false do not require value ranges and apply their effects directly.
#
# Example:
#   ModifyHealth:
#     rarities: [Magic, Rare, Epic, Legendary, Mythic]
#     weight: 1
#     hasValues: true
#     increment: 0.01
#     values:
#       Magic: [0.05, 0.1]
#       Rare: [0.1, 0.15]
#       Epic: [0.15, 0.2]
#       Legendary: [0.2, 0.25]
#       Mythic: [0.25, 0.3]


AddBluntResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Blunt"

AddBluntVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Blunt"

AddSlashResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Slash"

AddSlashVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Slash"

AddPierceResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Pierce"

AddPierceVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Pierce"

AddChopResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Chop"

AddChopVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Chop"

AddPickaxeResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Pickaxe"

AddPickaxeVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Pickaxe"

AddFireResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Fire"

AddFireVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Fire"

AddFrostResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Frost"

AddFrostVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Frost"

AddLightningResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Lightning"

AddLightningVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Lightning"

AddPoisonResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Poison"

AddPoisonVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Poison"

AddSpiritResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Spirit"

AddSpiritVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Spirit"

AddDamageResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Damage"

AddDamageVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Damage"

AddPhysicalResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Physical"

AddPhysicalVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Physical"

AddElementalResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Resistant: Elemental"

AddElementalVeryResistant:
  rarities: [Magic, Rare, Epic, Legendary, Mythic]
  weight: 1
  hasValues: false
  displayName: "Very Resistant: Elemental"

  # Continue for other modifiers if needed...
